<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CustomerOrders.Business\CustomerOrders.Business.csproj" />
      <ProjectReference Include="..\CustomerOrders.Domain\CustomerOrders.Domain.csproj" />
    </ItemGroup>

</Project>
